### ISSUE TITLE
"The app must perform all environment-specific logic at that point only." Confusing

### ISSUE THREAD

**Issue by justinyost** [beporter/CakePHP-EnvAwareness#1]
Ref: https://github.com/beporter/CakePHP-EnvAwareness/blob/a83170ddc7c6a8970471db04bac6a4f40d6867e2/slides/env-aware-cake-apps.md#env-specific-settings-are-checked-and-loaded-once

You say it should only perform all environment specific logic at that point only, but really everything is environment specific as defined by the APP_ENV, what you really mean is the application should figure out it's environment in one place and only one place.

**Comment by beporter** [comment]
Closed via 0c5e5d3(?)
